version: '3.4'
services:
  node:
    networks:
      - default
      - main
    image: "node:ubuntu"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - ./:/home/node/app
    ports:
      - "11111:80"
    command: "npm start"
    deploy:
      update_config:
        order: start-first

networks:
  main:
    external:
      name: main
